language: node_js
node_js:
  - "4.1"
  - "0.11"
  - "0.10"
before_install:
  - "npm install -g mocha voc"
  - "npm install blanket"
  - "npm install coveralls mocha-lcov-reporter"
before_script:
  - "voc codepage.md"
after_success:
  - "make coveralls-spin"
